packages:
  - "packages/*"
  - "docs"

engineStrict: true
linkWorkspacePackages: true
allowBuilds:
  esbuild: true
sharedWorkspaceLockfile: true
minimumReleaseAgeExclude:
  - '@ai-sdk/gateway@3.0.127'
  - ai@6.0.199
